### PR TITLE
feat(recoil): added recoil for global state management

### PR DESCRIPTION
**Pull request by dchueri**

### CODE REVIEW

**Review by daniloab — COMMENTED** [review]
why recoil?

**Comment by dchueri** [comment]
Initially, I've seen on https://twitter.com/sseraphini/status/1385561029778845698 that library is utilized to state management on React, so I decided to study this. But while I read the documentation I saw some differences between Recoil and Redux (my initial option), and one of the main ones that I found is the simplest implementation, even though it is in an experimental phase.

I don't know if it would be good to use it in a real project, but at least for studies I found it very interesting. I used it to manage the list of movies when the user adds and removes movies, later I think I can implement a subscribe from the relay. What do you think?

**Comment by daniloab** [comment]
> Initially, I've seen on https://twitter.com/sseraphini/status/1385561029778845698 that library is utilized to state management on React, so I decided to study this. But while I read the documentation I saw some differences between Recoil and Redux (my initial option), and one of the main ones that I found is the simplest implementation, even though it is in an experimental phase.
> 
> I don't know if it would be good to use it in a real project, but at least for studies I found it very interesting. I used it to manage the list of movies when the user adds and removes movies, later I think I can implement a subscribe from the relay. What do you think?

with relay you can avoid the use of state managers

for adding or removing a node in relay you can use appendEdge, deleteEdge, and other directives. Try to read about it

**Comment by dchueri** [comment]
Thx, I'll read about it right now

**Pull request merged**
